# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate profiling-procmacros

Name:           rust-%{crate}
Version:        1.0.3
Release:        1%{?dist}
Summary:        Very thin abstraction over other profiler crates

# Upstream license specification: MIT OR Apache-2.0
# FIXME: missing LICENSE files
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/profiling-procmacros
Source:         %{crates_source}
# Initial patched metadata
# * drop features for unavailable tracing backends
Patch0:         profiling-procmacros-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Very thin abstraction over other profiler crates.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+profile-with-tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+profile-with-tracing-devel %{_description}

This package contains library source intended for building other packages
which use "profile-with-tracing" feature of "%{crate}" crate.

%files       -n %{name}+profile-with-tracing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.3-1
- Update to version 1.0.3.

* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.1-1
- Initial package
