# Generated by rust2rpm 17
%bcond_without check

%global crate naga

Name:           rust-%{crate}
Version:        0.4.2
Release:        1%{?dist}
Summary:        Shader translation infrastructure

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/naga
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Shader translation infrastructure.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}
# FIXME: binary license

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{_bindir}/naga
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+codespan-reporting-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+codespan-reporting-devel %{_description}

This package contains library source intended for building other packages
which use "codespan-reporting" feature of "%{crate}" crate.

%files       -n %{name}+codespan-reporting-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+deserialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deserialize-devel %{_description}

This package contains library source intended for building other packages
which use "deserialize" feature of "%{crate}" crate.

%files       -n %{name}+deserialize-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dot-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dot-out-devel %{_description}

This package contains library source intended for building other packages
which use "dot-out" feature of "%{crate}" crate.

%files       -n %{name}+dot-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+glsl-in-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glsl-in-devel %{_description}

This package contains library source intended for building other packages
which use "glsl-in" feature of "%{crate}" crate.

%files       -n %{name}+glsl-in-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+glsl-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glsl-out-devel %{_description}

This package contains library source intended for building other packages
which use "glsl-out" feature of "%{crate}" crate.

%files       -n %{name}+glsl-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+glsl-validate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glsl-validate-devel %{_description}

This package contains library source intended for building other packages
which use "glsl-validate" feature of "%{crate}" crate.

%files       -n %{name}+glsl-validate-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hlsl-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hlsl-out-devel %{_description}

This package contains library source intended for building other packages
which use "hlsl-out" feature of "%{crate}" crate.

%files       -n %{name}+hlsl-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+msl-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+msl-out-devel %{_description}

This package contains library source intended for building other packages
which use "msl-out" feature of "%{crate}" crate.

%files       -n %{name}+msl-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+petgraph-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+petgraph-devel %{_description}

This package contains library source intended for building other packages
which use "petgraph" feature of "%{crate}" crate.

%files       -n %{name}+petgraph-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pomelo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pomelo-devel %{_description}

This package contains library source intended for building other packages
which use "pomelo" feature of "%{crate}" crate.

%files       -n %{name}+pomelo-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pp-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pp-rs-devel %{_description}

This package contains library source intended for building other packages
which use "pp-rs" feature of "%{crate}" crate.

%files       -n %{name}+pp-rs-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages
which use "serialize" feature of "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+spirv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spirv-devel %{_description}

This package contains library source intended for building other packages
which use "spirv" feature of "%{crate}" crate.

%files       -n %{name}+spirv-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+spv-in-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spv-in-devel %{_description}

This package contains library source intended for building other packages
which use "spv-in" feature of "%{crate}" crate.

%files       -n %{name}+spv-in-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+spv-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spv-out-devel %{_description}

This package contains library source intended for building other packages
which use "spv-out" feature of "%{crate}" crate.

%files       -n %{name}+spv-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+wgsl-in-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wgsl-in-devel %{_description}

This package contains library source intended for building other packages
which use "wgsl-in" feature of "%{crate}" crate.

%files       -n %{name}+wgsl-in-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+wgsl-out-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wgsl-out-devel %{_description}

This package contains library source intended for building other packages
which use "wgsl-out" feature of "%{crate}" crate.

%files       -n %{name}+wgsl-out-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.4.2-1
- Update to version 0.4.2.

* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.3.2-1
- Initial package
