# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate abort_on_panic

Name:           rust-%{crate}
Version:        2.0.0
Release:        1%{?dist}
Summary:        Intercept panic! from unsafe locations and abort the process

# Upstream license specification: CC0-1.0
License:        CC0
URL:            https://crates.io/crates/abort_on_panic
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Intercept panic! from unsafe locations and abort the process.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE.txt
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Sep 06 2021 Fabio Valentini <decathorpe@gmail.com> - 2.0.0-1
- Initial package
