# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate deno_doc

Name:           rust-%{crate}
Version:        0.4.0
Release:        1%{?dist}
Summary:        Doc generation for deno

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/deno_doc
Source:         %{crates_source}
# Initial patched metadata
# * relax regex dependency
Patch0:         deno_doc-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Doc generation for deno.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENCE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jun 05 2021 Fabio Valentini <decathorpe@gmail.com> - 0.4.0-1
- Update to version 0.4.0.

* Thu Apr 29 2021 Fabio Valentini <decathorpe@gmail.com> - 0.3.0-2
- Relax regex dependency.

* Thu Apr 22 2021 Fabio Valentini <decathorpe@gmail.com> - 0.3.0-1
- Initial package
