# Generated by rust2rpm 17
# * missing dev-dependencies
%bcond_with check
%global debug_package %{nil}

%global crate pharos

Name:           rust-%{crate}
Version:        0.5.1
Release:        1%{?dist}
Summary:        Observer pattern which generates a futures 0.3 stream of events

# Upstream license specification: Unlicense
License:        Unlicense
URL:            https://crates.io/crates/pharos
Source:         %{crates_source}
# Initial patched metadata
# * enable default features in futures
# * bump rustc_version from 0.2 to 0.3
Patch0:         pharos-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Observer pattern which generates a futures 0.3 stream of events.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Apr 29 2021 Fabio Valentini <decathorpe@gmail.com> - 0.5.1-1
- Initial package
