# Generated by rust2rpm 17
# * tests depend on unavailable tracing backends
%bcond_with check
%global debug_package %{nil}

%global crate profiling

Name:           rust-%{crate}
Version:        1.0.1
Release:        1%{?dist}
Summary:        Very thin abstraction over other profiler crates

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/profiling
Source:         %{crates_source}
# Initial patched metadata
# * drop features and dependencies for unavailable tracing backends
Patch0:         profiling-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Very thin abstraction over other profiler crates.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+procmacros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+procmacros-devel %{_description}

This package contains library source intended for building other packages
which use "procmacros" feature of "%{crate}" crate.

%files       -n %{name}+procmacros-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+profile-with-tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+profile-with-tracing-devel %{_description}

This package contains library source intended for building other packages
which use "profile-with-tracing" feature of "%{crate}" crate.

%files       -n %{name}+profile-with-tracing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+profiling-procmacros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+profiling-procmacros-devel %{_description}

This package contains library source intended for building other packages
which use "profiling-procmacros" feature of "%{crate}" crate.

%files       -n %{name}+profiling-procmacros-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages
which use "tracing" feature of "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+type-check-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+type-check-devel %{_description}

This package contains library source intended for building other packages
which use "type-check" feature of "%{crate}" crate.

%files       -n %{name}+type-check-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.1-1
- Initial package
