# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate pkcs5

Name:           rust-%{crate}
Version:        0.3.1
Release:        1%{?dist}
Summary:        Pure Rust implementation of PKCS#5 (RFC 8018)

# Upstream license specification: Apache-2.0 OR MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/pkcs5
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Pure Rust implementation of Public-Key Cryptography Standards (PKCS) #5:
Password-Based Cryptography Specification Version 2.1 (RFC 8018).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+aes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-devel %{_description}

This package contains library source intended for building other packages
which use "aes" feature of "%{crate}" crate.

%files       -n %{name}+aes-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+block-modes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+block-modes-devel %{_description}

This package contains library source intended for building other packages
which use "block-modes" feature of "%{crate}" crate.

%files       -n %{name}+block-modes-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hmac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hmac-devel %{_description}

This package contains library source intended for building other packages
which use "hmac" feature of "%{crate}" crate.

%files       -n %{name}+hmac-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pbes2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pbes2-devel %{_description}

This package contains library source intended for building other packages
which use "pbes2" feature of "%{crate}" crate.

%files       -n %{name}+pbes2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pbkdf2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pbkdf2-devel %{_description}

This package contains library source intended for building other packages
which use "pbkdf2" feature of "%{crate}" crate.

%files       -n %{name}+pbkdf2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+scrypt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scrypt-devel %{_description}

This package contains library source intended for building other packages
which use "scrypt" feature of "%{crate}" crate.

%files       -n %{name}+scrypt-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sha2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sha2-devel %{_description}

This package contains library source intended for building other packages
which use "sha2" feature of "%{crate}" crate.

%files       -n %{name}+sha2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.3.1-1
- Initial package
