# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate trust-dns-client

Name:           rust-%{crate}
Version:        0.20.3
Release:        1%{?dist}
Summary:        Trust-DNS is a safe and secure DNS library

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/trust-dns-client
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Trust-DNS is a safe and secure DNS library. This is the Client library with
DNSec support.  DNSSec with NSEC validation for negative records, is complete.
The client supports  dynamic DNS with SIG0 authenticated requests, implementing
easy to use high level  funtions. Trust-DNS is based on the Tokio and Futures
libraries, which means  it should be easily integrated into other software that
also use those  libraries.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+backtrace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+backtrace-devel %{_description}

This package contains library source intended for building other packages
which use "backtrace" feature of "%{crate}" crate.

%files       -n %{name}+backtrace-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-https-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-https-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-https" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-https-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-https-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-https-openssl-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-https-openssl" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-https-openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-https-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-https-rustls-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-https-rustls" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-https-rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-openssl-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-openssl" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-rustls-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-rustls" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dns-over-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-over-tls-devel %{_description}

This package contains library source intended for building other packages
which use "dns-over-tls" feature of "%{crate}" crate.

%files       -n %{name}+dns-over-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dnssec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dnssec-devel %{_description}

This package contains library source intended for building other packages
which use "dnssec" feature of "%{crate}" crate.

%files       -n %{name}+dnssec-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dnssec-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dnssec-openssl-devel %{_description}

This package contains library source intended for building other packages
which use "dnssec-openssl" feature of "%{crate}" crate.

%files       -n %{name}+dnssec-openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dnssec-ring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dnssec-ring-devel %{_description}

This package contains library source intended for building other packages
which use "dnssec-ring" feature of "%{crate}" crate.

%files       -n %{name}+dnssec-ring-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mdns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mdns-devel %{_description}

This package contains library source intended for building other packages
which use "mdns" feature of "%{crate}" crate.

%files       -n %{name}+mdns-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages
which use "openssl" feature of "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ring-devel %{_description}

This package contains library source intended for building other packages
which use "ring" feature of "%{crate}" crate.

%files       -n %{name}+ring-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages
which use "rustls" feature of "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-config-devel %{_description}

This package contains library source intended for building other packages
which use "serde-config" feature of "%{crate}" crate.

%files       -n %{name}+serde-config-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust-dns-https-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-https-devel %{_description}

This package contains library source intended for building other packages
which use "trust-dns-https" feature of "%{crate}" crate.

%files       -n %{name}+trust-dns-https-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+webpki-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-devel %{_description}

This package contains library source intended for building other packages
which use "webpki" feature of "%{crate}" crate.

%files       -n %{name}+webpki-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# skip tests that time out in mock environment
%cargo_test -- -- --skip "src/lib.rs"
%endif

%changelog
* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.20.3-1
- Update to version 0.20.3.

* Thu Apr 29 2021 Fabio Valentini <decathorpe@gmail.com> - 0.20.2-1
- Initial package
