# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate sourcemap

Name:           rust-%{crate}
Version:        6.0.1
Release:        1%{?dist}
Summary:        Basic sourcemap handling for Rust

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            https://crates.io/crates/sourcemap
Source:         %{crates_source}
# Initial patched metadata
# * bump rustc_version from 0.2.3 to 0.3 (FIXME)
Patch0:         sourcemap-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Basic sourcemap handling for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ram_bundle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ram_bundle-devel %{_description}

This package contains library source intended for building other packages
which use "ram_bundle" feature of "%{crate}" crate.

%files       -n %{name}+ram_bundle-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+scroll-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scroll-devel %{_description}

This package contains library source intended for building other packages
which use "scroll" feature of "%{crate}" crate.

%files       -n %{name}+scroll-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Apr 20 2021 Fabio Valentini <decathorpe@gmail.com> - 6.0.1-1
- Initial package
