# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate deno_webstorage

Name:           rust-%{crate}
Version:        0.11.0
Release:        1%{?dist}
Summary:        Implementation of WebStorage API for Deno

# Upstream license specification: MIT
# FIXME: missing LICENSE file
License:        MIT
URL:            https://crates.io/crates/deno_webstorage
Source:         %{crates_source}
# Initial patched metadata
# * temporarily downgrade rusqlite from 0.25 to 0.24
# * disable bundled libsqlite3 feature of rusqlite
Patch0:         deno_webstorage-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Implementation of WebStorage API for Deno.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.11.0-1
- Update to version 0.11.0.

* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.1-1
- Initial package
