# Generated by rust2rpm 18
# * testing and testing_macros rely on unstable proc-macro2 features
%bcond_with check
%global debug_package %{nil}

%global crate swc_bundler

Name:           rust-%{crate}
Version:        0.50.0
Release:        1%{?dist}
Summary:        Very fast ecmascript bundler

# Upstream license specification: Apache-2.0/MIT
# FIXME: missing LICENSE files
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/swc_bundler
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Very fast ecmascript bundler.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+concurrent-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+concurrent-devel %{_description}

This package contains library source intended for building other packages
which use "concurrent" feature of "%{crate}" crate.

%files       -n %{name}+concurrent-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dashmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dashmap-devel %{_description}

This package contains library source intended for building other packages
which use "dashmap" feature of "%{crate}" crate.

%files       -n %{name}+dashmap-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages
which use "rayon" feature of "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.50.0-1
- Update to version 0.50.0.

* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.34.0-1
- Update to version 0.34.0.

* Thu Apr 29 2021 Fabio Valentini <decathorpe@gmail.com> - 0.32.8-1
- Update to version 0.32.8.

* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.32.5-1
- Initial package
