# Generated by rust2rpm 18
# * dev-dependencies are outdated
%bcond_with check
%global debug_package %{nil}

%global crate ws_stream_tungstenite

Name:           rust-%{crate}
Version:        0.6.1
Release:        1%{?dist}
Summary:        Provide AsyncRead/AsyncWrite over Tungstenite WebSockets

# Upstream license specification: Unlicense
License:        Unlicense
URL:            https://crates.io/crates/ws_stream_tungstenite
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Provide AsyncRead/AsyncWrite over Tungstenite WebSockets.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages
which use "tokio" feature of "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio_io-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio_io-devel %{_description}

This package contains library source intended for building other packages
which use "tokio_io" feature of "%{crate}" crate.

%files       -n %{name}+tokio_io-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.6.1-1
- Update to version 0.6.1.

* Thu Apr 29 2021 Fabio Valentini <decathorpe@gmail.com> - 0.6.0-1
- Initial package
