# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate webpki

Name:           rust-%{crate}
Version:        0.21.4
Release:        1%{?dist}
Summary:        Web PKI X.509 Certificate Verification

# Upstream license specification: None
# * webpki itself is licensed under the terms of the ISC license
# * third-party data from chromium is licensed under a 3-Clause BSD license,
#   but it is only used for integration tests and not included in RPM packages
License:        ISC

URL:            https://crates.io/crates/webpki
Source:         %{crates_source}
# Initial patched metadata
# * bump base64 from 0.9 to 0.13 (FIXME)
Patch0:         webpki-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
# ring is not available on ppc64le and s390x
ExcludeArch:    ppc64le s390x
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Web PKI X.509 Certificate Verification.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/
# these files are only used by integration tests
%exclude %{cargo_registry}/%{crate}-%{version_no_tilde}/third-party/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trust_anchor_util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust_anchor_util-devel %{_description}

This package contains library source intended for building other packages
which use "trust_anchor_util" feature of "%{crate}" crate.

%files       -n %{name}+trust_anchor_util-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.21.4-1
- Initial package
