# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate rspirv

Name:           rust-%{crate}
Version:        0.7.0
Release:        1%{?dist}
Summary:        Rust library APIs for SPIR-V module manipulation

# Upstream license specification: Apache-2.0
# FIXME: missing license file
License:        ASL 2.0
URL:            https://crates.io/crates/rspirv
Source:         %{crates_source}
# Initial patched metadata
# * drop optional clippy feature
Patch0:         rspirv-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust library APIs for SPIR-V module manipulation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.7.0-1
- Initial package
