# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate value-bag

Name:           rust-%{crate}
Version:        1.0.0~alpha.6
Release:        1%{?dist}
Summary:        Anonymous structured values

# Upstream license specification: Apache-2.0 OR MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/value-bag
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Anonymous structured values.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+erased-serde1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+erased-serde1-devel %{_description}

This package contains library source intended for building other packages
which use "erased-serde1" feature of "%{crate}" crate.

%files       -n %{name}+erased-serde1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+error-devel %{_description}

This package contains library source intended for building other packages
which use "error" feature of "%{crate}" crate.

%files       -n %{name}+error-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde1-devel %{_description}

This package contains library source intended for building other packages
which use "serde1" feature of "%{crate}" crate.

%files       -n %{name}+serde1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde1_fmt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde1_fmt-devel %{_description}

This package contains library source intended for building other packages
which use "serde1_fmt" feature of "%{crate}" crate.

%files       -n %{name}+serde1_fmt-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde1_lib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde1_lib-devel %{_description}

This package contains library source intended for building other packages
which use "serde1_lib" feature of "%{crate}" crate.

%files       -n %{name}+serde1_lib-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sval-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sval-devel %{_description}

This package contains library source intended for building other packages
which use "sval" feature of "%{crate}" crate.

%files       -n %{name}+sval-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sval1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sval1-devel %{_description}

This package contains library source intended for building other packages
which use "sval1" feature of "%{crate}" crate.

%files       -n %{name}+sval1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sval1_lib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sval1_lib-devel %{_description}

This package contains library source intended for building other packages
which use "sval1_lib" feature of "%{crate}" crate.

%files       -n %{name}+sval1_lib-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+test-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-devel %{_description}

This package contains library source intended for building other packages
which use "test" feature of "%{crate}" crate.

%files       -n %{name}+test-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%ifarch aarch64
# FIXME: one failing memory layout test on aarch64
%cargo_test -- -- --skip tests::value_bag_size
%else
%cargo_test
%endif
%endif

%changelog
* Sun Apr 18 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.0~alpha.6-1
- Initial package
