# Generated by rust2rpm 18
# * tests use loom
%bcond_with check
%global debug_package %{nil}

%global crate wgpu-core

Name:           rust-%{crate}
Version:        0.9.2
Release:        1%{?dist}
Summary:        WebGPU core logic on gfx-hal

# Upstream license specification: MIT OR Apache-2.0
# FIXME: missing LICENSE files
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/wgpu-core
Source:         %{crates_source}
# Initial patched metadata
# * drop windows-, WASM-, and mac OS-specific dependencies and features
# * drop unused loom dev-dependency
Patch0:         wgpu-core-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
WebGPU core logic on gfx-hal.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+raw-window-handle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+raw-window-handle-devel %{_description}

This package contains library source intended for building other packages
which use "raw-window-handle" feature of "%{crate}" crate.

%files       -n %{name}+raw-window-handle-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+replay-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+replay-devel %{_description}

This package contains library source intended for building other packages
which use "replay" feature of "%{crate}" crate.

%files       -n %{name}+replay-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ron-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ron-devel %{_description}

This package contains library source intended for building other packages
which use "ron" feature of "%{crate}" crate.

%files       -n %{name}+ron-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serial-pass-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serial-pass-devel %{_description}

This package contains library source intended for building other packages
which use "serial-pass" feature of "%{crate}" crate.

%files       -n %{name}+serial-pass-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace-devel %{_description}

This package contains library source intended for building other packages
which use "trace" feature of "%{crate}" crate.

%files       -n %{name}+trace-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Sep 06 2021 Fabio Valentini <decathorpe@gmail.com> - 0.9.2-1
- Update to version 0.9.2.

* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.8.1-1
- Update to version 0.8.1.

* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.7.1-1
- Initial package
