# Generated by rust2rpm 16
# * needs to be ported from futures-channel-preview to futures-channel
%bcond_with check
%global debug_package %{nil}

%global crate wasm-bindgen-futures

Name:           rust-%{crate}
Version:        0.4.23
Release:        1%{?dist}
Summary:        Bridging the gap between Rust Futures and JavaScript Promises

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/wasm-bindgen-futures
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Bridging the gap between Rust Futures and JavaScript Promises.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages
which use "futures-core" feature of "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-core-03-stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-03-stream-devel %{_description}

This package contains library source intended for building other packages
which use "futures-core-03-stream" feature of "%{crate}" crate.

%files       -n %{name}+futures-core-03-stream-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Mar 31 2021 Fabio Valentini <decathorpe@gmail.com> - 0.4.23-1
- Initial package
