# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate rusty_v8

Name:           rust-%{crate}
Version:        0.22.3
Release:        1%{?dist}
Summary:        Rust bindings to V8

# Upstream license specification: MIT
# FIXME: missing license files
License:        MIT
URL:            https://crates.io/crates/rusty_v8
Source:         %{crates_source}
# Initial patched metadata
# * drop unused fslock build-dependency
Patch0:         rusty_v8-fix-metadata.diff
# build system adaptations
# * build using system clang
# * build bundled v8 from source
Patch1:         0001-use-system-clang-and-build-v8-from-source-once.patch

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  python3-devel
BuildRequires:  rust-packaging

%global _description %{expand:
Rust bindings to V8.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

# require statically linked v8 library
# * v8 has to be compiled only *once* here
# * saves build resources in dependent packages
Requires:       %{name}-static-v8

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}-static-v8
Summary:        %{summary}

# v8                    BSD
# icu                   BSD
# jinja2                BSD
# markupsafe            BSD
# zlib                  zlib
# inspector_protocol    MIT
# wasm-api              ASL 2.0
# siphash               CC0
# utf8-decoder          MIT
# valgrind.h            BSD
# vtune                 BSD or GPLv2
License:        BSD and zlib and MIT and ASL 2.0 and CC0

Provides:       bundled(v8) = 9.1.269.35

# https://github.com/denoland/rusty_v8/tree/v0.22.1/third_party
# https://github.com/denoland/icu/tree/28b0e9e
Provides:       bundled(icu) = 28b0e9e
Provides:       bundled(jinja2) = 2.10
Provides:       bundled(markupsafe) = 0.18
Provides:       bundled(zlib) = e84c9a3

# https://github.com/denoland/chromium_buildtools/tree/ccba851/third_party
Provides:       bundled(libc++) = 8fa8794
Provides:       bundled(libc++abi) = 196ba1a

# https://chromium.googlesource.com/v8/v8/+/399148/third_party/
Provides:       bundled(inspector_protocol)
# https://github.com/WebAssembly/wasm-c-api/tree/6db391e
Provides:       bundled(wasm-api) = 6db391e

# https://chromium.googlesource.com/v8/v8/+/399148/src/third_party/
Provides:       bundled(siphash)
Provides:       bundled(utf8-decoder)

%description -n %{name}-static-v8 %{_description}

This package contains the statically linked v8 library, so dependent
packages can be built without having to recompile v8 itself every time.

%files       -n %{name}-static-v8
%dir %{_libdir}/%{crate}
%{_libdir}/%{crate}/v%{version_no_tilde}

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1

# drop test that needs data not shipped with published crates
rm tests/test_api.rs

# drop trybuild tests that fail with cosmetic string differences
rm tests/test_ui.rs
rm -r tests/compile_fail

# remove bundled pre-built binaries
rm buildtools/third_party/eu-strip/bin/eu-strip

# fix python shebangs
pathfix.py -i /usr/bin/python3 -pn $(find -type f ! -name "*.js")

%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

echo '/usr/bin/clang'
echo '/usr/bin/gn'
echo '/usr/bin/lld'
echo '/usr/bin/llvm-ar'
echo '/usr/bin/ninja'
echo '/usr/bin/python'

echo 'pkgconfig(glib-2.0)'
echo 'pkgconfig(gmodule-2.0)'
echo 'pkgconfig(gobject-2.0)'
echo 'pkgconfig(gthread-2.0)'

%build
# build bundled V8 from source
export V8_FROM_SOURCE=1
# show build script output for internal v8 build
%cargo_build -- -vv

%install
%cargo_install

# ship static v8 library so dependent packages don't have to recompile it
mkdir -p %{buildroot}/%{_libdir}/%{crate}/v%{version_no_tilde}

cp -pav target/release/gn_out/obj/lib%{crate}.a \
    %{buildroot}/%{_libdir}/%{crate}/v%{version_no_tilde}/lib%{crate}.a

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jun 20 2021 Fabio Valentini <decathorpe@gmail.com> - 0.22.3-1
- Update to version 0.22.3.

* Tue May 25 2021 Fabio Valentini <decathorpe@gmail.com> - 0.22.2-1
- Update to version 0.22.2.

* Sun Apr 18 2021 Fabio Valentini <decathorpe@gmail.com> - 0.22.1-1
- Initial package
