# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global __cargo_is_bin() false

%global crate lexical

Name:           rust-%{crate}
Version:        5.2.2
Release:        1%{?dist}
Summary:        To- and from-string conversion routines

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/lexical
Source:         %{crates_source}
# Initial patched metadata
# * bump approx from 0.4 to 0.5
# * drop bench-only criterion dev-dependency
Patch0:         lexical-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
To- and from-string conversion routines.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+comprehensive_float_test-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+comprehensive_float_test-devel %{_description}

This package contains library source intended for building other packages
which use "comprehensive_float_test" feature of "%{crate}" crate.

%files       -n %{name}+comprehensive_float_test-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+correct-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+correct-devel %{_description}

This package contains library source intended for building other packages
which use "correct" feature of "%{crate}" crate.

%files       -n %{name}+correct-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+format-devel %{_description}

This package contains library source intended for building other packages
which use "format" feature of "%{crate}" crate.

%files       -n %{name}+format-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+grisu3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grisu3-devel %{_description}

This package contains library source intended for building other packages
which use "grisu3" feature of "%{crate}" crate.

%files       -n %{name}+grisu3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libm-devel %{_description}

This package contains library source intended for building other packages
which use "libm" feature of "%{crate}" crate.

%files       -n %{name}+libm-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+noinline-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+noinline-devel %{_description}

This package contains library source intended for building other packages
which use "noinline" feature of "%{crate}" crate.

%files       -n %{name}+noinline-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+property_tests-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+property_tests-devel %{_description}

This package contains library source intended for building other packages
which use "property_tests" feature of "%{crate}" crate.

%files       -n %{name}+property_tests-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+radix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+radix-devel %{_description}

This package contains library source intended for building other packages
which use "radix" feature of "%{crate}" crate.

%files       -n %{name}+radix-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages
which use "rand" feature of "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rounding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rounding-devel %{_description}

This package contains library source intended for building other packages
which use "rounding" feature of "%{crate}" crate.

%files       -n %{name}+rounding-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ryu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ryu-devel %{_description}

This package contains library source intended for building other packages
which use "ryu" feature of "%{crate}" crate.

%files       -n %{name}+ryu-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_derive-devel %{_description}

This package contains library source intended for building other packages
which use "serde_derive" feature of "%{crate}" crate.

%files       -n %{name}+serde_derive-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+toml-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+toml-devel %{_description}

This package contains library source intended for building other packages
which use "toml" feature of "%{crate}" crate.

%files       -n %{name}+toml-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+trim_floats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trim_floats-devel %{_description}

This package contains library source intended for building other packages
which use "trim_floats" feature of "%{crate}" crate.

%files       -n %{name}+trim_floats-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unchecked_index-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unchecked_index-devel %{_description}

This package contains library source intended for building other packages
which use "unchecked_index" feature of "%{crate}" crate.

%files       -n %{name}+unchecked_index-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 07 2021 Fabio Valentini <decathorpe@gmail.com> - 5.2.2-1
- Initial package
