# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate deno-libffi-sys

Name:           rust-%{crate}
Version:        0.0.7
Release:        1%{?dist}
Summary:        Raw Rust bindings for libffi

# Upstream license specification: MIT/Apache-2.0
# FIXME: missing LICENSE files
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/deno-libffi-sys
Source:         %{crates_source}
# Initial patched metadata
# * always link against system libffi
Patch0:         deno-libffi-sys-fix-metadata.diff
Patch1:         0001-always-link-against-system-libffi.patch

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Raw Rust bindings for libffi.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+complex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+complex-devel %{_description}

This package contains library source intended for building other packages
which use "complex" feature of "%{crate}" crate.

%files       -n %{name}+complex-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+system-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       libffi-devel

%description -n %{name}+system-devel %{_description}

This package contains library source intended for building other packages
which use "system" feature of "%{crate}" crate.

%files       -n %{name}+system-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
# remove bundled libffi sources
rm -r libffi
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
echo 'libffi-devel'

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Sep 06 2021 Fabio Valentini <decathorpe@gmail.com> - 0.0.7-1
- Initial package
