# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate dprint-core

Name:           rust-%{crate}
Version:        0.38.0
Release:        1%{?dist}
Summary:        Core rust library for dprint

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/dprint-core
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Core rust library for dprint.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bumpalo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bumpalo-devel %{_description}

This package contains library source intended for building other packages
which use "bumpalo" feature of "%{crate}" crate.

%files       -n %{name}+bumpalo-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+fnv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fnv-devel %{_description}

This package contains library source intended for building other packages
which use "fnv" feature of "%{crate}" crate.

%files       -n %{name}+fnv-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+formatting-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+formatting-devel %{_description}

This package contains library source intended for building other packages
which use "formatting" feature of "%{crate}" crate.

%files       -n %{name}+formatting-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+process-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+process-devel %{_description}

This package contains library source intended for building other packages
which use "process" feature of "%{crate}" crate.

%files       -n %{name}+process-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages
which use "serde_json" feature of "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+sysinfo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sysinfo-devel %{_description}

This package contains library source intended for building other packages
which use "sysinfo" feature of "%{crate}" crate.

%files       -n %{name}+sysinfo-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages
which use "tracing" feature of "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-devel %{_description}

This package contains library source intended for building other packages
which use "wasm" feature of "%{crate}" crate.

%files       -n %{name}+wasm-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.38.0-1
- Update to version 0.38.0.

* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.35.3-1
- Initial package
