# Generated by rust2rpm 20
%bcond_without check
%global debug_package %{nil}

%global crate ast_node

Name:           rust-%{crate}
Version:        0.7.6
Release:        1%{?dist}
Summary:        Macros for ast nodes

# Upstream license specification: Apache-2.0
# FIXME: missing license file
License:        ASL 2.0
URL:            https://crates.io/crates/ast_node
Source:         %{crates_source}
# Initial patched metadata
# * bump darling from 0.10 to 0.12 (FIXME)
Patch0:         ast_node-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Macros for ast nodes.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 06 2022 Fabio Valentini <decathorpe@gmail.com> - 0.7.6-1
- Update to version 0.7.6.

* Thu Apr 22 2021 Fabio Valentini <decathorpe@gmail.com> - 0.7.3-1
- Initial package
