# Generated by rust2rpm 17
# * gl dev-dependency not packaged yet
%bcond_with check
%global debug_package %{nil}

%global crate khronos-egl

Name:           rust-%{crate}
Version:        4.1.0
Release:        1%{?dist}
Summary:        Rust bindings for EGL

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/khronos-egl
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust bindings for EGL.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_0-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_0-devel %{_description}

This package contains library source intended for building other packages
which use "1_0" feature of "%{crate}" crate.

%files       -n %{name}+1_0-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_1-devel %{_description}

This package contains library source intended for building other packages
which use "1_1" feature of "%{crate}" crate.

%files       -n %{name}+1_1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_2-devel %{_description}

This package contains library source intended for building other packages
which use "1_2" feature of "%{crate}" crate.

%files       -n %{name}+1_2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_3-devel %{_description}

This package contains library source intended for building other packages
which use "1_3" feature of "%{crate}" crate.

%files       -n %{name}+1_3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_4-devel %{_description}

This package contains library source intended for building other packages
which use "1_4" feature of "%{crate}" crate.

%files       -n %{name}+1_4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+1_5-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+1_5-devel %{_description}

This package contains library source intended for building other packages
which use "1_5" feature of "%{crate}" crate.

%files       -n %{name}+1_5-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dynamic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dynamic-devel %{_description}

This package contains library source intended for building other packages
which use "dynamic" feature of "%{crate}" crate.

%files       -n %{name}+dynamic-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libloading-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libloading-devel %{_description}

This package contains library source intended for building other packages
which use "libloading" feature of "%{crate}" crate.

%files       -n %{name}+libloading-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+no-pkg-config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no-pkg-config-devel %{_description}

This package contains library source intended for building other packages
which use "no-pkg-config" feature of "%{crate}" crate.

%files       -n %{name}+no-pkg-config-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pkg-config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkg-config-devel %{_description}

This package contains library source intended for building other packages
which use "pkg-config" feature of "%{crate}" crate.

%files       -n %{name}+pkg-config-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+static-devel %{_description}

This package contains library source intended for building other packages
which use "static" feature of "%{crate}" crate.

%files       -n %{name}+static-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jun 07 2021 Fabio Valentini <decathorpe@gmail.com> - 4.1.0-1
- Update to version 4.1.0.

* Fri Apr 23 2021 Fabio Valentini <decathorpe@gmail.com> - 3.0.2-1
- Initial package
